### ISSUE TITLE
BCM43142 802.11b/g/n (Broadcom) wireless driver not installed Manjaro XFCE 0.8.13.1 in Acer E5-521G-871K

### ISSUE THREAD

**Issue by filipe-marques** [manjaro/mhwd#19]
I just bought a Acer E5-521G-871K laptop and install, in dual boot with Windows 8.1, Manjaro XFCE 0.8.13.1 x64 bits with Linux Kernel 3.18.
When I was updating for the first time I notice that only wired networks where recognized and not wireless and in the Net Cafe they have a new router.
I check also if the problem was from the new router but isn't. The wireless network works in Windows 8.1.
So I go to Manjaro Settings Manager and notice that the Broadcom wireless driver wasn't installed (see image 1).
I saw that there exist a linux kernel module for Broadcom: linux318-broadcom-wl  6.30.223.248-1 so if I install this I get the problem solved ?
I have this linux module installed linux318-ndiswrapper  1.59-11, so it will conflict with linux318-broadcom-wl  6.30.223.248-1 if I install it ?
I check by typing in a terminal window: lspci -k and I have the kernel module loaded and in use for Broadcom and the wireless network doesn't work. (see image 2)

Thanks in advance
![notwirelessdriverinstalled](https://cloud.githubusercontent.com/assets/3500553/9994932/7af751fa-6077-11e5-92f2-e018cc49ae27.png)
![kernelmodulesnetworkinuse](https://cloud.githubusercontent.com/assets/3500553/9994942/85c4c658-6077-11e5-8ef8-4c3cf71ec001.png)

**Comment by philmmanjaro** [comment]
Always provide the output of:
```
mhwd
mhwd -lh
hwinfo --wlan
hwinfo --network
```

**Comment by filipe-marques** [comment]
Do I need to uninstall linux318-ndiswrapper 1.59-11 and install linux318-broadcom-wl 6.30.223.248-1 or updating the linux kernel to 4.2.1 to a newer one ?

![mhwd](https://cloud.githubusercontent.com/assets/3500553/10021093/2ee8dcb2-613e-11e5-9ed9-6163982a8d93.png)
![mhwdlh](https://cloud.githubusercontent.com/assets/3500553/10021100/3a253d0a-613e-11e5-87ea-203ce138e97f.png)
![ms](https://cloud.githubusercontent.com/assets/3500553/10021123/5256d9e2-613e-11e5-927b-bc8c82c3c45e.png)
![hwinfonetwork](https://cloud.githubusercontent.com/assets/3500553/10021136/6140ebaa-613e-11e5-9ad0-0252a8366c12.png)
![hwinfowlan](https://cloud.githubusercontent.com/assets/3500553/10021137/61695a86-613e-11e5-9f6a-d40c06c4d49b.png)

**Comment by filipe-marques** [comment]
```
[filipe@fm ~]$ lspci
00:00.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Device 1566
00:01.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Mullins [Radeon R4/R5 Graphics] (rev 05)
00:01.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Kabini HDMI/DP Audio
00:02.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Device 156b
00:02.1 PCI bridge: Advanced Micro Devices, Inc. [AMD] Family 16h Processor Functions 5:1
00:02.3 PCI bridge: Advanced Micro Devices, Inc. [AMD] Family 16h Processor Functions 5:1
00:02.4 PCI bridge: Advanced Micro Devices, Inc. [AMD] Family 16h Processor Functions 5:1
00:08.0 Encryption controller: Advanced Micro Devices, Inc. [AMD] Device 1537
00:10.0 USB controller: Advanced Micro Devices, Inc. [AMD] FCH USB XHCI Controller (rev 11)
00:11.0 SATA controller: Advanced Micro Devices, Inc. [AMD] FCH SATA Controller [AHCI mode] (rev 40)
00:12.0 USB controller: Advanced Micro Devices, Inc. [AMD] FCH USB EHCI Controller (rev 39)
00:13.0 USB controller: Advanced Micro Devices, Inc. [AMD] FCH USB EHCI Controller (rev 39)
00:14.0 SMBus: Advanced Micro Devices, Inc. [AMD] FCH SMBus Controller (rev 42)
00:14.2 Audio device: Advanced Micro Devices, Inc. [AMD] FCH Azalia Controller (rev 02)
00:14.3 ISA bridge: Advanced Micro Devices, Inc. [AMD] FCH LPC Bridge (rev 11)
00:14.7 SD Host controller: Advanced Micro Devices, Inc. [AMD] FCH SD Flash Controller (rev 01)
00:18.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Device 1580
00:18.1 Host bridge: Advanced Micro Devices, Inc. [AMD] Device 1581
00:18.2 Host bridge: Advanced Micro Devices, Inc. [AMD] Device 1582
00:18.3 Host bridge: Advanced Micro Devices, Inc. [AMD] Device 1583
00:18.4 Host bridge: Advanced Micro Devices, Inc. [AMD] Device 1584
00:18.5 Host bridge: Advanced Micro Devices, Inc. [AMD] Device 1585
01:00.0 Display controller: Advanced Micro Devices, Inc. [AMD/ATI] Jet XT [Radeon R5 M240] (rev ff)
02:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. Device 5287 (rev 01)
02:00.1 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 12)
03:00.0 Network controller: Broadcom Corporation BCM43142 802.11b/g/n (rev 01)
```

**Comment by filipe-marques** [comment]
I just remember that I install Manjaro using the first boot option: Free Drivers - Do I need to repeat the installation with Non Free Drivers ?

**Comment by philmmanjaro** [comment]
I think we don't check for class **280** in our broadcom driver. Can you post `mhwd -lh` in text please. If your wlan works with the **wl** driver, then you're fine. However your hardware don't get detected so far. I'll fix that soon.

**Comment by filipe-marques** [comment]
I will test by installing the linux318-broadcom-wl 6.30.223.248-1 package and I hope that will not conflict with the package linux318-ndiswrapper 1.59-11 already installed and I will post the result of mhwd -lh in text soon, because I'm in a pc with Windows
