### ISSUE TITLE
Fix copyright declaration

### ISSUE THREAD

**Issue by 2mac** [manjaro/mhwd#22]
Surely this software's copyright is not held by the FSF, and surely it wasn't written only in 2007.

Please fix the copyright information in the source code's license headers. The GPLv3 is copyright 2007 by the FSF, but not this program.

**Comment by philmmanjaro** [comment]
Current copyright is: `Copyright © 2012 - 2016 Manjaro (http://manjaro.org)`

**Comment by 2mac** [comment]
Yes, but the source file headers do not reflect this, and they should. You are erroneously saying to people who read that header that this program is copyright 2007 Free Software Foundation, which is not the case.
