### ISSUE TITLE
Kernels >=4.5 missing ACPI handles for laptops.

### ISSUE THREAD

**Issue by NovaCygni** [manjaro/mhwd#23]
All kernels 4.4 and below are unaffected, this is likely a small oversite but:
acpi_toshiba handle is missing, this is used by all APU and mCPU laptops made by Toshiba and other brands that use the acpi_toshiba kernel flag... this is quite a serious issue as without the acpi_toshiba flag set in the kernel the laptop forces the processor to run at full speed constantly which they are not intended to do... a Toshiba C50d laptop will reach 72'c "Idling" on desktop due to this issue, same on the other 4 Satellites ive tested it on aswell. Downgrading to 4.4 solved the serious issue (* auto-heat shutdowns constantly, it froze 5 times due to the heat issue simply in the time it takes to install a lower kernel version :/ *)
Idle desktop Temp with 4.4 Kernels and below = 44'c
Idle desktop Temp with 4.5 Kernel and above = 72~'C, GPU causes vga_Leakage errors, System freezes due to temprature, General severe overheating issues.

**Comment by philmmanjaro** [comment]
Be more specific what is broken. I know you're facing thermal issues using newer kernels than **4.4.x** series. I checked our config files and compared them. The specific **acpi_toshiba** configuration I also don't find in the older configs. So I need an error message or something to tackle your issue ...

**Comment by philmmanjaro** [comment]
The module is compiled as modular module:

```
[phil@manjaro 16.06-rc1]$ zcat /proc/config.gz | grep TOSHIBA
CONFIG_YENTA_TOSHIBA=y
CONFIG_PATA_TOSHIBA=m
CONFIG_MMC_TOSHIBA_PCI=m
CONFIG_ACPI_TOSHIBA=m
CONFIG_TOSHIBA_BT_RFKILL=m
CONFIG_TOSHIBA_HAPS=m
CONFIG_TOSHIBA_WMI=m
[phil@manjaro 16.06-rc1]$ uname -a
Linux manjaro 4.5.4-1-MANJARO #1 SMP PREEMPT Wed May 11 22:58:41 UTC 2016 x86_64 GNU/Linux
```

What happens if you do `sudo modprobe toshiba_acpi`?

```
[phil@manjaro 16.06-rc1]$ pacman -Ql linux45 | grep toshiba
linux45 /usr/lib/modules/4.5.4-1-MANJARO/kernel/drivers/platform/x86/toshiba-wmi.ko.gz
linux45 /usr/lib/modules/4.5.4-1-MANJARO/kernel/drivers/platform/x86/toshiba_acpi.ko.gz
linux45 /usr/lib/modules/4.5.4-1-MANJARO/kernel/drivers/platform/x86/toshiba_bluetooth.ko.gz
linux45 /usr/lib/modules/4.5.4-1-MANJARO/kernel/drivers/platform/x86/toshiba_haps.ko.gz
```

**Comment by NovaCygni** [comment]
:\ CPU at 82'c hopefully can post all this without it freezing again.... 
sudo modprobe toshiba_acpi "APPEARS" to be accepted fine, but it is 100% NOT fine, as fnfx gives:

`fatal error: Could open /proc/acpi/toshiba/keys.
Please make sure that your kernel has enabled the Toshiba option in the ACPI section.
`

Tested this on the C35d, C35a and 2 other Toshiba Satellites, its affecting ALL toshibas using the toshiba_acpi/fnfxd kernel flags.... 

Restested on every kernel available, can confirm 100% none below or equal to 4.5 version are affected, the modprobe command works fine as it appears to on the affected versions but unlike 4.5/4.6, the ACPI is working as CPU/Fan isnt being forced to 100%.

It would appear that the toshiba_acpi is either being loaded MisNamed thus the fnfx and other services requiring it are unable to use it, as the acpi should by Toshibas design lock any APU's to there LOWEST clock rate at boot and only increase the speed/fan speed depending on the "PowerState"/"CpuLoadDemand" ratio.

PS> Worth noting aswell only the 4.5+ Kernels, also present a "Leaked on vgs invocation." error, in WALLS of of it aswell, during the installation, seems to affect all the APU based Toshibas, unsure if its related but the Kernels that work fine, dont present this WallOfErrors during installation.

**Comment by philmmanjaro** [comment]
Is this issue still relevant?

**Comment by NovaCygni** [comment]
Nope was fixed a month after I posted this.
